CREATE TABLE `employee` (
  `id` int(12) NOT NULL AUTO_INCREMENT,
  `fname` varchar(50) DEFAULT NULL,
  `lname` varchar(45) DEFAULT NULL,
  `middle` varchar(45) DEFAULT NULL,
  `email_personal` varchar(45) DEFAULT NULL,
  `direct_number` varchar(45) DEFAULT NULL,
  `cell_number` varchar(20) DEFAULT NULL,
  `date_create` varchar(45) DEFAULT NULL,
  `division` varchar(45) DEFAULT NULL,
  `date_expire` varchar(45) DEFAULT NULL,
  `fax` int(20) DEFAULT NULL,
  `emp_ID` varchar(45) DEFAULT NULL,
  `email_group` varchar(45) DEFAULT NULL,
  `home_number` varchar(45) DEFAULT NULL,
  `title` varchar(45) DEFAULT NULL,
  `man` varchar(45) DEFAULT NULL,
  `not_ID` varchar(45) DEFAULT NULL,
  `office` int(30) DEFAULT NULL,
  `security` varchar(45) DEFAULT NULL,
  `status` tinyint(4) DEFAULT NULL,
  `superV` varchar(45) DEFAULT NULL,
  `username` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
